sudo: required

language: generic

service:
  - docker

before-install:
  - docker build -t kb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-356095541420"
  bucket_path: "frontend"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master  